window.esdocSearchIndex = [
  [
    "@moqada/hubot-schedule-helper/src/errors.js~alreadypassedpattern",
    "class/src/errors.js~AlreadyPassedPattern.html",
    "<span>AlreadyPassedPattern</span> <span class=\"search-result-import-path\">@moqada/hubot-schedule-helper/src/errors.js</span>",
    "class"
  ],
  [
    "@moqada/hubot-schedule-helper/src/errors.js~invalidpattern",
    "class/src/errors.js~InvalidPattern.html",
    "<span>InvalidPattern</span> <span class=\"search-result-import-path\">@moqada/hubot-schedule-helper/src/errors.js</span>",
    "class"
  ],
  [
    "@moqada/hubot-schedule-helper/src/job.js~job",
    "class/src/Job.js~Job.html",
    "<span>Job</span> <span class=\"search-result-import-path\">@moqada/hubot-schedule-helper/src/Job.js</span>",
    "class"
  ],
  [
    "@moqada/hubot-schedule-helper/src/errors.js~jobnotfound",
    "class/src/errors.js~JobNotFound.html",
    "<span>JobNotFound</span> <span class=\"search-result-import-path\">@moqada/hubot-schedule-helper/src/errors.js</span>",
    "class"
  ],
  [
    "@moqada/hubot-schedule-helper/src/scheduler.js~scheduler",
    "class/src/Scheduler.js~Scheduler.html",
    "<span>Scheduler</span> <span class=\"search-result-import-path\">@moqada/hubot-schedule-helper/src/Scheduler.js</span>",
    "class"
  ],
  [
    "@moqada/hubot-schedule-helper/src/utils.js~difference",
    "function/index.html#static-function-difference",
    "<span>difference</span> <span class=\"search-result-import-path\">@moqada/hubot-schedule-helper/src/utils.js</span>",
    "function"
  ],
  [
    "@moqada/hubot-schedule-helper/src/utils.js~getpatterntype",
    "function/index.html#static-function-getPatternType",
    "<span>getPatternType</span> <span class=\"search-result-import-path\">@moqada/hubot-schedule-helper/src/utils.js</span>",
    "function"
  ],
  [
    "@moqada/hubot-schedule-helper/src/utils.js~iscronpattern",
    "function/index.html#static-function-isCronPattern",
    "<span>isCronPattern</span> <span class=\"search-result-import-path\">@moqada/hubot-schedule-helper/src/utils.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "scheduler src/scheduler.js~scheduler,scheduler",
    "test-file/test/Scheduler-spec.js.html#lineNumber7",
    "Scheduler",
    "test"
  ],
  [
    "scheduler#canceljob src/scheduler.js~scheduler#canceljob,scheduler#canceljob",
    "test-file/test/Scheduler-spec.js.html#lineNumber95",
    "Scheduler #cancelJob()",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber109",
    "Scheduler #cancelJob() JobNotFound",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber101",
    "Scheduler #cancelJob() canceled",
    "test"
  ],
  [
    "scheduler#createjob src/scheduler.js~scheduler#createjob,scheduler#createjob",
    "test-file/test/Scheduler-spec.js.html#lineNumber64",
    "Scheduler #createJob()",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber70",
    "Scheduler #createJob() pattern: * 0 * * *",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber81",
    "Scheduler #createJob() pattern: 2016-02-20",
    "test"
  ],
  [
    "scheduler#syncbrain src/scheduler.js~scheduler#syncbrain,scheduler#syncbrain",
    "test-file/test/Scheduler-spec.js.html#lineNumber142",
    "Scheduler #syncBrain()",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber157",
    "Scheduler #syncBrain() on brain.loaded",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber148",
    "Scheduler #syncBrain() sync brain data",
    "test"
  ],
  [
    "scheduler#updatejob src/scheduler.js~scheduler#updatejob,scheduler#updatejob",
    "test-file/test/Scheduler-spec.js.html#lineNumber117",
    "Scheduler #updateJob()",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber134",
    "Scheduler #updateJob() JobNotFound",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber123",
    "Scheduler #updateJob() updated",
    "test"
  ],
  [
    "scheduler#constructor src/scheduler.js~scheduler#constructor,scheduler#constructor",
    "test-file/test/Scheduler-spec.js.html#lineNumber41",
    "Scheduler constructor()",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber48",
    "Scheduler constructor() instance",
    "test"
  ],
  [
    "",
    "test-file/test/Scheduler-spec.js.html#lineNumber55",
    "Scheduler constructor() set brain.loaded",
    "test"
  ],
  [
    "src/job.js",
    "file/src/Job.js.html",
    "src/Job.js",
    "file"
  ],
  [
    "src/job.js~job#cancel",
    "class/src/Job.js~Job.html#instance-method-cancel",
    "src/Job.js~Job#cancel",
    "method"
  ],
  [
    "src/job.js~job#cb",
    "class/src/Job.js~Job.html#instance-member-cb",
    "src/Job.js~Job#cb",
    "member"
  ],
  [
    "src/job.js~job#constructor",
    "class/src/Job.js~Job.html#instance-constructor-constructor",
    "src/Job.js~Job#constructor",
    "method"
  ],
  [
    "src/job.js~job#exec",
    "class/src/Job.js~Job.html#instance-method-exec",
    "src/Job.js~Job#exec",
    "method"
  ],
  [
    "src/job.js~job#getenvelope",
    "class/src/Job.js~Job.html#instance-method-getEnvelope",
    "src/Job.js~Job#getEnvelope",
    "method"
  ],
  [
    "src/job.js~job#getroom",
    "class/src/Job.js~Job.html#instance-method-getRoom",
    "src/Job.js~Job#getRoom",
    "method"
  ],
  [
    "src/job.js~job#id",
    "class/src/Job.js~Job.html#instance-member-id",
    "src/Job.js~Job#id",
    "member"
  ],
  [
    "src/job.js~job#job",
    "class/src/Job.js~Job.html#instance-member-job",
    "src/Job.js~Job#job",
    "member"
  ],
  [
    "src/job.js~job#meta",
    "class/src/Job.js~Job.html#instance-member-meta",
    "src/Job.js~Job#meta",
    "member"
  ],
  [
    "src/job.js~job#pattern",
    "class/src/Job.js~Job.html#instance-member-pattern",
    "src/Job.js~Job#pattern",
    "member"
  ],
  [
    "src/job.js~job#serialize",
    "class/src/Job.js~Job.html#instance-method-serialize",
    "src/Job.js~Job#serialize",
    "method"
  ],
  [
    "src/job.js~job#start",
    "class/src/Job.js~Job.html#instance-method-start",
    "src/Job.js~Job#start",
    "method"
  ],
  [
    "src/job.js~job#user",
    "class/src/Job.js~Job.html#instance-member-user",
    "src/Job.js~Job#user",
    "member"
  ],
  [
    "src/scheduler.js",
    "file/src/Scheduler.js.html",
    "src/Scheduler.js",
    "file"
  ],
  [
    "src/scheduler.js~scheduler#jobcls",
    "class/src/Scheduler.js~Scheduler.html#instance-member-JobCls",
    "src/Scheduler.js~Scheduler#JobCls",
    "member"
  ],
  [
    "src/scheduler.js~scheduler#canceljob",
    "class/src/Scheduler.js~Scheduler.html#instance-method-cancelJob",
    "src/Scheduler.js~Scheduler#cancelJob",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#constructor",
    "class/src/Scheduler.js~Scheduler.html#instance-constructor-constructor",
    "src/Scheduler.js~Scheduler#constructor",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#createcronjob",
    "class/src/Scheduler.js~Scheduler.html#instance-method-createCronJob",
    "src/Scheduler.js~Scheduler#createCronJob",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#createdatejob",
    "class/src/Scheduler.js~Scheduler.html#instance-method-createDateJob",
    "src/Scheduler.js~Scheduler#createDateJob",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#createid",
    "class/src/Scheduler.js~Scheduler.html#instance-method-createId",
    "src/Scheduler.js~Scheduler#createId",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#createjob",
    "class/src/Scheduler.js~Scheduler.html#instance-method-createJob",
    "src/Scheduler.js~Scheduler#createJob",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#createjobfrombrain",
    "class/src/Scheduler.js~Scheduler.html#instance-method-createJobFromBrain",
    "src/Scheduler.js~Scheduler#createJobFromBrain",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#initbrain",
    "class/src/Scheduler.js~Scheduler.html#instance-method-initBrain",
    "src/Scheduler.js~Scheduler#initBrain",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#jobmaxcount",
    "class/src/Scheduler.js~Scheduler.html#instance-member-jobMaxCount",
    "src/Scheduler.js~Scheduler#jobMaxCount",
    "member"
  ],
  [
    "src/scheduler.js~scheduler#jobs",
    "class/src/Scheduler.js~Scheduler.html#instance-member-jobs",
    "src/Scheduler.js~Scheduler#jobs",
    "member"
  ],
  [
    "src/scheduler.js~scheduler#robot",
    "class/src/Scheduler.js~Scheduler.html#instance-member-robot",
    "src/Scheduler.js~Scheduler#robot",
    "member"
  ],
  [
    "src/scheduler.js~scheduler#storejobtobrain",
    "class/src/Scheduler.js~Scheduler.html#instance-method-storeJobToBrain",
    "src/Scheduler.js~Scheduler#storeJobToBrain",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#storekey",
    "class/src/Scheduler.js~Scheduler.html#instance-member-storeKey",
    "src/Scheduler.js~Scheduler#storeKey",
    "member"
  ],
  [
    "src/scheduler.js~scheduler#syncbrain",
    "class/src/Scheduler.js~Scheduler.html#instance-method-syncBrain",
    "src/Scheduler.js~Scheduler#syncBrain",
    "method"
  ],
  [
    "src/scheduler.js~scheduler#updatejob",
    "class/src/Scheduler.js~Scheduler.html#instance-method-updateJob",
    "src/Scheduler.js~Scheduler#updateJob",
    "method"
  ],
  [
    "src/errors.js",
    "file/src/errors.js.html",
    "src/errors.js",
    "file"
  ],
  [
    "src/errors.js~alreadypassedpattern#constructor",
    "class/src/errors.js~AlreadyPassedPattern.html#instance-constructor-constructor",
    "src/errors.js~AlreadyPassedPattern#constructor",
    "method"
  ],
  [
    "src/errors.js~alreadypassedpattern#name",
    "class/src/errors.js~AlreadyPassedPattern.html#instance-member-name",
    "src/errors.js~AlreadyPassedPattern#name",
    "member"
  ],
  [
    "src/errors.js~invalidpattern#constructor",
    "class/src/errors.js~InvalidPattern.html#instance-constructor-constructor",
    "src/errors.js~InvalidPattern#constructor",
    "method"
  ],
  [
    "src/errors.js~invalidpattern#name",
    "class/src/errors.js~InvalidPattern.html#instance-member-name",
    "src/errors.js~InvalidPattern#name",
    "member"
  ],
  [
    "src/errors.js~jobnotfound#constructor",
    "class/src/errors.js~JobNotFound.html#instance-constructor-constructor",
    "src/errors.js~JobNotFound#constructor",
    "method"
  ],
  [
    "src/errors.js~jobnotfound#name",
    "class/src/errors.js~JobNotFound.html#instance-member-name",
    "src/errors.js~JobNotFound#name",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ],
  [
    "test/scheduler-spec.js",
    "test-file/test/Scheduler-spec.js.html",
    "test/Scheduler-spec.js",
    "testFile"
  ]
]